// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTE5f4LWIdyicod46rXNtFvJ1oO4uxbc',
    appId: '1:294705622166:web:6b691fe4ae5d6a79a026b7',
    messagingSenderId: '294705622166',
    projectId: 'flutter-firebase-appjam',
    authDomain: 'flutter-firebase-appjam.firebaseapp.com',
    storageBucket: 'flutter-firebase-appjam.appspot.com',
    measurementId: 'G-QJ6E6ZYB8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMfD7-Gcwx5uAv5GlfNtrpab4qtE_lw8',
    appId: '1:294705622166:android:d397ad83b59afc70a026b7',
    messagingSenderId: '294705622166',
    projectId: 'flutter-firebase-appjam',
    storageBucket: 'flutter-firebase-appjam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rC6Nl6J9_qGxc-BkxnM30FUntty0Iu4',
    appId: '1:294705622166:ios:36a90f5ce991e76ea026b7',
    messagingSenderId: '294705622166',
    projectId: 'flutter-firebase-appjam',
    storageBucket: 'flutter-firebase-appjam.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8rC6Nl6J9_qGxc-BkxnM30FUntty0Iu4',
    appId: '1:294705622166:ios:1668c5e9de065e22a026b7',
    messagingSenderId: '294705622166',
    projectId: 'flutter-firebase-appjam',
    storageBucket: 'flutter-firebase-appjam.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
